FROM nginx:1.27-alpine

# Удаляем дефолтный конфиг и копируем свой (необязательно)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем статические файлы
COPY frontend/ /usr/share/nginx/html

EXPOSE 80
